from Receta import Receta

pan = Receta("pan casero", "sencilla", "5 horas")
pan.añadirIngrediente("harina", 500, "gr")
pan.añadirIngrediente("agua", 250, "ml")
pan.añadirIngrediente("levadura seca de panadero", 5, "gr")
pan.añadirIngrediente("sal", 8, "gr")
pan.añadirInstruccion("En un bol poner la levadura, un poquito del agua y un poquito de la harina.")
pan.añadirInstruccion("Dejar reposar unos 15 minutos")
pan.añadirInstruccion("Añadir el resto de la harina, del agua y la sal.")
pan.añadirInstruccion("Mezclar bien. Al principio con una mano sujetando el bol y con la otra mezclando. Una vez la masa no pringa, se pueden usar las dos manos para amasar.")
pan.añadirInstruccion("Trabajar la masa durante unos 10 minutos, amasandola con las manos.")
pan.añadirInstruccion("Dar forma a la masa y dejarla dormir durante unas tres horas o más. Bien arropadita: en lugar cálido y sin corrientes de aire.")
pan.añadirInstruccion("Precalentar el horno a unos 250 grados centígrados.")
pan.añadirInstruccion("Poner la masa sobre una bandeja (o sobre rejilla con papel de horno). Hacerle unos cortes con una cuchilla de afeitar. Meterla al horno, durante unos 20 minutos.")
pan.añadirInstruccion("Dejar enfriar, sobre una rejilla, durante una media hora como mínimo.")

lentejas = Receta("lentejas con verduras", "sencilla", "2 horas y media")
lentejas.añadirIngrediente("lentejas", 200, "gr")
lentejas.añadirIngrediente("agua", 1, "suficiente")
lentejas.añadirIngrediente("zanahorias", 100, "gr")
lentejas.añadirInstruccion("Poner las lentejas en una cazuela, cubrir con agua (unos dos o tres dedos de agua por encima de las lentejas).")
lentejas.añadirInstruccion("Dejar remojar en frio, como mínimo unos 15 minutos.")
lentejas.añadirInstruccion("Cocer, a fuego medio, durante una hora o así. Remover de vez en cuando. Añadir agua cuando falte.")
lentejas.añadirInstruccion("Poner un puñado de sal y un chorrito de aceite.")
lentejas.añadirInstruccion("Poner las zanahorias, cortadas en dados. (Se pueden poner también otras verduras.)")
lentejas.añadirInstruccion("Seguir cociendo, a fuego lento, durante otra hora o así. Remover de vez en cuando. Añádir agua si faltara.")
